### ISSUE TITLE
Load NvJpeg still not stable (0.0.9)

### ISSUE THREAD

**Issue by maara-fieldtrip** [UsingNet/nvjpeg-python#2]
Unfortunately I'm still seeing this in 0.0.9 when using in a ROS process, sometimes it errors out with:

`SystemError: <class 'nvjpeg.NvJpeg'> returned NULL without setting an error`

Most of the time runs, approximately 1/5 times I get this error on startup when I call `  nvjpeg.NvJpeg()`

**Comment by saulzar** [comment]
It seems to happen much more often when called from in a thread, too - more like 4/5 times.

**Comment by saulzar** [comment]
I'm trying to understand what's going on here - what is actually being set to NULL here? It's the NvJpeg python object not the m_handle inside it? The pointer returned from NvJpegPython_startUpEnv never seems to be NULL so what is?

It seems to be some kind of race condition because if I put a printf inside NvJpeg_init I never get the error.

**Comment by saulzar** [comment]
A modification of the test-with-multiprocessing.py which reliably produces the error

```
from nvjpeg import NvJpeg 
nj = NvJpeg()   <--- add this line in immediately after import in the main thread
```

**Comment by saulzar** [comment]
In fact it doesn't even need to run the threads at all. This is the full test case:

```
from nvjpeg import NvJpeg 
nj = NvJpeg()
```

Gives the error ~50% of the time

**Comment by saulzar** [comment]
See pull request I made a fix but it's just sitting there

**Comment by chrischengis** [comment]
Thanks saulzar!

Zeng, when do you expect the release with this fix be available?

**Comment by zengohm** [comment]
> Thanks saulzar!
> 
> Zeng, when do you expect the release with this fix be available?

Thanks  chrischengis!
I have merged and released this fix.
