### ISSUE TITLE
Is NVIDIA Jetson SoCs in nvjpeg-python Roadmap

### ISSUE THREAD

**Issue by di55olve88** [UsingNet/nvjpeg-python#3]
Hello,

I've had a great experience with nvjpeg-python and have been wondering if there are plans to port it to the NVIDIA Jetson SoC platforms that are based on aarch64 and tegra kernel.

**Comment by zengohm** [comment]
Nvjpeg in cuda is not similar with nvjpeg in L4T Multimedia API.
I will try to implement it with L4T Multimedia API.

**Comment by zengohm** [comment]
> Hello,
> 
> I've had a great experience with nvjpeg-python and have been wondering if there are plans to port it to the NVIDIA Jetson SoC platforms that are based on aarch64 and tegra kernel.

The last version 0.0.12 has been release.
I have tested in NVIDIA Jetson AGX Xavier.
