### ISSUE TITLE
 ERROR: Failed building wheel for pynvjpeg

### ISSUE THREAD

**Issue by advanced373** [UsingNet/nvjpeg-python#5]
Hi,

I'm trying to install this module, but I received  ERROR: Failed building wheel for pynvjpeg - nvjpeg-python.c(2): fatal error C1083: Cannot open include file: 'nvjpeg.h': No such file or directory. I mentioned that I have cuda toolkit 11.0, OS Windows, Python 3.9.

**Comment by zengohm** [comment]
This package has not been tested on Windows, I will get back to you after testing it.

**Comment by zengohm** [comment]
Can you find the file in "NVIDIA GPU Computing Toolkit\CUDA\{YOUR CUDA VERSION}\include\nvjpeg.h" ?

**Comment by advanced373** [comment]
Yes, I found it.

**Comment by zeng-qinghui** [comment]
> Yes, I found it.

I updated it. 
The version 0.0.13 can be built in Windows.

**Comment by nistarlwc** [comment]
How to install in windows10 with cuda 11.2?  

src\x86\JpegCoder.cpp(2): fatal error C1083:  “nvjpeg.h”: No such file or directory
      error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
