### ISSUE TITLE
可以支持下返回的是一个在GPU上的torch tensor么？

### ISSUE THREAD

**Issue by zkwangchao** [UsingNet/nvjpeg-python#6]
目前支持解码完返回一个numpy array，可以支持返回一个torch的tensor么？谢谢

**Comment by zeng-qinghui** [comment]
torch中有转换函数把numpy array转换成tensor
```python
torch.from_numpy(a_numpy_array)
```

**Comment by zkwangchao** [comment]
> torch中有转换函数把numpy array转换成tensor
> 
> ```python
> torch.from_numpy(a_numpy_array)
> ```

`

**Comment by zkwangchao** [comment]
再从torch 转的话，需要重新cpu->gpu之间的数据copy，会对预测性能有影响
